# Generated by Django 5.1.5 on 2025-04-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicschema",
            name="count",
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
    ]
