# Generated by Django 5.1.5 on 2025-04-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_dynamicschema_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicschema",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
