# Generated by Django 5.1.5 on 2025-04-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_dynamicschema_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type",
            name="type",
            field=models.CharField(
                choices=[
                    ("CharField", "CharField"),
                    ("TextField", "TextField"),
                    ("IntegerField", "IntegerField"),
                    ("BooleanField", "BooleanField"),
                    ("ImageField", "ImageField"),
                    ("DateField", "DateField"),
                ],
                db_index=True,
                default="CharField",
                max_length=255,
            ),
        ),
    ]
