# Generated by Django 5.1.5 on 2025-04-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_type_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="type",
            name="type",
            field=models.CharField(
                choices=[
                    ("CharField", "CharField"),
                    ("TextField", "TextField"),
                    ("IntegerField", "IntegerField"),
                    ("FloatField", "FloatField"),
                    ("BooleanField", "BooleanField"),
                    ("DateField", "DateField"),
                    ("DateTimeField", "DateTimeField"),
                    ("TimeField", "TimeField"),
                    ("EmailField", "EmailField"),
                    ("URLField", "URLField"),
                    ("SlugField", "SlugField"),
                    ("UUIDField", "UUIDField"),
                    ("ImageField", "ImageField"),
                    ("FileField", "FileField"),
                    ("DecimalField", "DecimalField"),
                    ("IPAddressField", "IPAddressField"),
                    ("GenericIPAddressField", "GenericIPAddressField"),
                    ("PhoneNumberField", "PhoneNumberField"),
                    ("BinaryField", "BinaryField"),
                    ("DurationField", "DurationField"),
                    ("JSONField", "JSONField"),
                    ("SmallIntegerField", "SmallIntegerField"),
                    ("PositiveIntegerField", "PositiveIntegerField"),
                    ("PositiveSmallIntegerField", "PositiveSmallIntegerField"),
                    ("BigIntegerField", "BigIntegerField"),
                ],
                db_index=True,
                default="CharField",
                max_length=255,
            ),
        ),
    ]
